[package]
name = "ellie_native_bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
enum-as-inner = { version = "0.6.1", optional = true }

[features]
default = ["rust_bridge"]
rust_bridge = ["enum-as-inner"]

[lib]
crate-type = ["rlib", "dylib"]

